version: "3"
services:
  angular:
    command: "tail -f /dev/null"
    image: "node:8-alpine"
    ports:
      - "4200:4200"
      - "9876:9876"
    user: "node"
    volumes:
      - "./:/home/node/my-app"
    working_dir: "/home/node/my-app"
